import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { Footer, Header, MobileBar } from "@/components/SiteChrome";
function NotFound(){return <div className="grid min-h-screen place-items-center bg-background px-4 text-center"><div><p className="eyebrow">404</p><h1 className="display-hero mt-4 text-7xl">PAGE NOT FOUND</h1><Link to="/" className="mt-7 inline-flex bg-primary px-6 py-3 text-xs font-bold text-primary-foreground">GO HOME</Link></div></div>}
function ErrorPage({error,reset}:{error:Error;reset:()=>void}){const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:"tanstack_root_error_component"}),[error]);return <div className="grid min-h-screen place-items-center px-4 text-center"><div><h1 className="display-hero text-6xl">THIS PAGE DIDN'T LOAD</h1><button onClick={()=>{router.invalidate();reset()}} className="mt-6 bg-primary px-6 py-3 text-xs font-bold text-primary-foreground">TRY AGAIN</button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{name:"theme-color",content:"#090908"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=Manrope:wght@400;500;600;700&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:Shell,component:Root,notFoundComponent:NotFound,errorComponent:ErrorPage});
function Shell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function Root(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Header/><Outlet/><Footer/><MobileBar/></QueryClientProvider>}
