import { ArrowDown, Clock3, MapPin } from "lucide-react";
import { Atmosphere } from "./Atmosphere";
import { ActionLink } from "./Button";
import { FinalCta, ProgramsGrid } from "./PageBlocks";
import { Reveal } from "./Reveal";
import { features, gymConfig, images, pricingPlans, testimonials } from "@/data/site";

export function HomePage() {
  return <main>
    <section className="relative min-h-[100svh] overflow-hidden bg-background">
      <img src={images.heroImage} width={1920} height={1088} fetchPriority="high" alt="Athlete performing a focused dumbbell curl at Aura Fitness" className="absolute inset-0 size-full object-cover object-[62%_center] opacity-80 md:object-center"/>
      <div className="absolute inset-0 bg-linear-to-r from-background via-background/70 to-transparent"/><div className="absolute inset-0 bg-linear-to-t from-background via-transparent to-background/25"/><div className="noise absolute inset-0 opacity-25"/><Atmosphere />
      <div className="section-shell relative z-10 flex min-h-[100svh] items-end pb-24 pt-32 md:items-center md:pb-8"><div className="max-w-3xl"><Reveal><p className="eyebrow">AURA FITNESS · SAMALKOTA</p><h1 className="display-hero mt-5 text-[clamp(4.5rem,12vw,10rem)]">AURA <span className="text-primary">FITNESS</span></h1><p className="mt-3 font-display text-2xl font-bold uppercase tracking-[.04em] md:text-4xl">{gymConfig.position}</p><p className="mt-3 text-xs font-bold tracking-[.22em] text-primary">{gymConfig.tagline}</p><p className="mt-6 max-w-xl text-sm leading-7 text-muted-foreground md:text-base">Train harder. Move stronger. Become better. A premium unisex fitness environment built for people who take their fitness seriously.</p><div className="mt-8 flex flex-wrap gap-3"><ActionLink to="/contact">Join Now</ActionLink><ActionLink to="/pricing" variant="outline">View Plans</ActionLink></div><div className="mt-8 flex flex-wrap gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Clock3 className="size-4 text-primary"/>5 AM – 1 PM · 5 PM – 9 PM</span><span className="flex items-center gap-2"><MapPin className="size-4 text-primary"/>Samalkota</span></div></Reveal></div></div>
      <div className="absolute bottom-5 right-8 z-10 hidden items-center gap-3 text-[.6rem] font-bold tracking-[.2em] text-muted-foreground md:flex">SCROLL TO EXPLORE <span className="animate-line block h-12 w-px bg-primary"/><ArrowDown className="size-3"/></div>
    </section>

    <section className="py-24 md:py-36"><div className="section-shell grid items-center gap-12 md:grid-cols-[.85fr_1.15fr]"><Reveal><div className="relative"><img loading="lazy" width={1200} height={1504} src={images.welcomeImage} alt="Athlete preparing a barbell in a premium gym" className="aspect-[4/5] w-full object-cover"/><div className="absolute -bottom-4 -right-4 h-1/2 w-px bg-primary"/></div></Reveal><Reveal><p className="eyebrow">WELCOME TO AURA</p><h2 className="display-hero mt-5 text-[clamp(4rem,8vw,7.5rem)]">TRAIN DIFFERENT.<br/><span className="text-primary">LIVE STRONGER.</span></h2><div className="gold-rule my-7 w-32"/><p className="max-w-xl text-base leading-8 text-muted-foreground">Aura Fitness is built for people who want more from their training — more strength, more discipline, more energy and better results.</p><p className="mt-5 max-w-xl text-sm leading-7 text-muted-foreground">Founded by {gymConfig.founder}, Aura Fitness is designed as a unisex fitness destination for the Samalkota community.</p><ActionLink to="/about" variant="outline" className="mt-8">Our Story</ActionLink></Reveal></div></section>

    <section className="bg-surface py-24 md:py-32"><div className="section-shell"><Reveal><p className="eyebrow">BUILT FOR PROGRESS</p><h2 className="display-hero mt-4 text-6xl md:text-8xl">WHY AURA?</h2></Reveal><div className="mt-14 grid md:grid-cols-2 lg:grid-cols-3">{features.map(([n,title,copy],i)=><Reveal key={n} delay={i*.04}><article className="group min-h-64 border-b border-border p-6 transition-colors hover:bg-surface-high md:border-r"><span className="font-display text-5xl text-gold-dim group-hover:text-primary">{n}</span><h3 className="mt-8 font-display text-2xl font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article></Reveal>)}</div></div></section>

    <section className="border-y border-border py-14"><div className="section-shell grid grid-cols-2 gap-y-8 md:grid-cols-4">{[["PREMIUM","ENVIRONMENT"],["UNISEX","COMMUNITY"],["5+","PROGRAMS"],["100%","FITNESS FOCUSED"]].map(([a,b])=><div key={b} className="border-l border-primary pl-4"><div className="font-display text-4xl font-extrabold text-primary md:text-6xl">{a}</div><div className="mt-1 text-[.6rem] font-bold tracking-[.15em] text-muted-foreground">{b}</div></div>)}</div></section>

    <section className="py-24 md:py-36"><div className="section-shell"><Reveal><p className="eyebrow">FIND YOUR TRAINING</p><div className="mt-4 flex items-end justify-between gap-5"><h2 className="display-hero text-6xl md:text-8xl">MOVE WITH<br/><span className="text-primary">PURPOSE.</span></h2><p className="hidden max-w-sm text-sm text-muted-foreground md:block">Different goals. One place to become stronger.</p></div></Reveal><div className="mt-12"><ProgramsGrid /></div><ActionLink to="/programs" variant="outline" className="mt-8">Explore Programs</ActionLink></div></section>

    <section className="relative flex min-h-[72svh] items-center overflow-hidden"><img loading="lazy" width={1600} height={1072} src={images.gymImage} alt="Premium Aura Fitness training floor" className="absolute inset-0 size-full object-cover opacity-45"/><div className="absolute inset-0 bg-background/55"/><div className="section-shell relative"><Reveal><p className="eyebrow">THE AURA MINDSET</p><h2 className="display-hero mt-5 max-w-5xl text-[clamp(4rem,10vw,8rem)]">DISCIPLINE<br/><span className="text-primary">CREATES RESULTS.</span></h2><p className="mt-8 font-display text-xl font-bold uppercase leading-9 text-muted-foreground">Show up. Put in the work.<br/>Stay consistent. Become stronger.</p></Reveal></div></section>

    <section className="bg-surface py-24 md:py-32"><div className="section-shell"><Reveal><p className="eyebrow">MEMBERSHIP</p><h2 className="display-hero mt-4 text-6xl md:text-8xl">CHOOSE YOUR<br/><span className="text-primary">COMMITMENT.</span></h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-5">{pricingPlans.map(plan=><article key={plan.term} className={`relative border p-6 ${plan.featured?"border-primary bg-primary/8":"border-border bg-card"}`}><p className="text-[.62rem] font-bold tracking-[.16em] text-primary">{plan.featured?"LIMITED OFFER":"MEMBERSHIP"}</p><h3 className="mt-8 font-display text-2xl font-bold">{plan.term}</h3><p className="mt-3 font-display text-4xl font-extrabold">{plan.price}</p><p className="mt-4 min-h-10 text-xs leading-5 text-muted-foreground">{plan.note??"Full gym access"}</p>{plan.badge&&<span className="mt-4 inline-block border border-primary px-2 py-1 text-[.55rem] font-bold text-primary">{plan.badge}</span>}</article>)}</div><ActionLink to="/pricing" className="mt-8">View Memberships</ActionLink></div></section>

    <section className="py-24"><div className="section-shell"><p className="eyebrow">REAL STORIES, COMING SOON</p><div className="mt-8 grid gap-4 md:grid-cols-2">{testimonials.map(item=><blockquote key={item.quote} className="border-l border-primary bg-card p-8"><div className="font-display text-7xl leading-none text-primary">“</div><p className="font-display text-3xl font-bold uppercase">{item.quote}</p><footer className="mt-6 text-xs tracking-[.14em] text-muted-foreground">{item.name} · {item.detail}</footer></blockquote>)}</div></div></section>
    <FinalCta />
  </main>;
}
