import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { useEffect, useState } from "react";
import { ActionLink } from "./Button";
import { Reveal } from "./Reveal";
import { galleryImages, gymConfig, images, pricingPlans, programs, trainers } from "@/data/site";

export function PageHero({ eyebrow, title, copy, image = images.gymImage }: { eyebrow: string; title: string; copy: string; image?: string }) {
  return <section className="relative flex min-h-[76svh] items-end overflow-hidden pt-28"><img src={image} alt="Aura Fitness training environment" className="absolute inset-0 size-full object-cover opacity-55"/><div className="absolute inset-0 bg-linear-to-t from-background via-background/55 to-background/20"/><div className="noise absolute inset-0 opacity-20"/><div className="section-shell relative z-10 pb-16 md:pb-24"><p className="eyebrow">{eyebrow}</p><h1 className="display-hero mt-5 max-w-5xl text-[clamp(4rem,12vw,9rem)] text-balance">{title}</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">{copy}</p></div></section>;
}

export function FinalCta() { return <section className="relative overflow-hidden border-t border-border py-24 md:py-36"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_50%,color-mix(in_oklab,var(--primary)_12%,transparent),transparent_35%)]"/><div className="section-shell relative"><Reveal><p className="eyebrow">START TODAY</p><h2 className="display-hero mt-5 max-w-5xl text-[clamp(4rem,10vw,8rem)]">YOUR STRONGER<br/><span className="text-primary">SELF STARTS HERE.</span></h2><p className="mt-7 max-w-md leading-7 text-muted-foreground">Train with purpose. Build strength. Become Aura.</p><div className="mt-9 flex flex-wrap gap-3"><ActionLink to="/contact">Join Aura Fitness</ActionLink><a href={`tel:${gymConfig.phone}`} className="inline-flex min-h-12 items-center border border-border px-6 text-xs font-bold tracking-[.16em] hover:border-primary">CALL {gymConfig.phoneDisplay}</a></div></Reveal></div></section>; }

export function ProgramsGrid() { return <div className="grid gap-3 md:grid-cols-6">{programs.map((program,index) => <Reveal key={program.name} className={`${index < 2 ? "md:col-span-3" : "md:col-span-2"}`} delay={index*.05}><article className="group relative min-h-[24rem] overflow-hidden border border-border bg-card"><img loading="lazy" width={1600} height={1200} src={images.programsImage} alt={`${program.name} training at Aura Fitness`} className="absolute inset-0 size-full object-cover transition-transform duration-500 group-hover:scale-105" style={{ objectPosition: program.position }}/><div className="absolute inset-0 bg-linear-to-t from-background via-background/40 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><span className="text-xs font-bold text-primary">{program.number}</span><h3 className="mt-2 font-display text-4xl font-bold uppercase">{program.name}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground opacity-90">{program.copy}</p></div></article></Reveal>)}</div>; }

export function PricingDisplay() { return <div className="grid border-t border-border">{pricingPlans.map(plan => <div key={plan.term} className={`grid items-center gap-4 border-b border-border px-1 py-6 md:grid-cols-[1fr_1fr_auto] md:px-6 ${plan.featured ? "animate-gold bg-primary/8" : "hover:bg-surface"}`}><div><span className="text-[.65rem] font-bold tracking-[.16em] text-primary">{plan.featured ? "LIMITED LAUNCH OFFER" : "MEMBERSHIP"}</span><h3 className="mt-1 font-display text-3xl font-bold">{plan.term}</h3></div><div className="text-sm text-muted-foreground">{plan.note ?? "Full gym access"}{plan.badge && <span className="ml-3 border border-primary px-2 py-1 text-[.6rem] font-bold text-primary">{plan.badge}</span>}</div><div className="font-display text-5xl font-extrabold text-primary">{plan.price}</div></div>)}</div>; }

export function TrainerGrid() { return <div className="grid gap-4 md:grid-cols-3">{trainers.map((trainer,i) => <Reveal key={trainer.name} delay={i*.08}><article className="group relative min-h-[34rem] overflow-hidden border border-border bg-card"><img loading="lazy" width={1200} height={1504} src={images.welcomeImage} alt="Editable trainer profile placeholder" className="absolute inset-0 size-full object-cover transition-transform duration-500 group-hover:scale-105" style={{ objectPosition: `${35+i*22}% center`, filter: i === 1 ? "grayscale(1)" : undefined }}/><div className="absolute inset-0 bg-linear-to-t from-background via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><p className="text-xs font-bold tracking-[.14em] text-primary">{trainer.specialty}</p><h3 className="mt-2 font-display text-3xl font-bold">{trainer.name}</h3><p className="mt-2 text-sm text-muted-foreground">{trainer.bio}</p></div></article></Reveal>)}</div>; }

export function GalleryGrid() {
  const [active,setActive] = useState<number | null>(null);
  useEffect(() => { const onKey=(event:KeyboardEvent)=>{ if(active===null)return; if(event.key==="Escape")setActive(null); if(event.key==="ArrowRight")setActive((active+1)%galleryImages.length); if(event.key==="ArrowLeft")setActive((active-1+galleryImages.length)%galleryImages.length); }; window.addEventListener("keydown",onKey); return()=>window.removeEventListener("keydown",onKey); },[active]);
  return <><div className="grid auto-rows-[15rem] gap-3 md:grid-cols-3">{galleryImages.map((image,i)=><button key={`${image.alt}-${i}`} type="button" onClick={()=>setActive(i)} className={`group relative overflow-hidden border border-border ${i===0||i===5?"md:col-span-2":""} ${i===1||i===4?"md:row-span-2":""}`} aria-label={`View ${image.alt}`}><img loading="lazy" width={1600} height={1200} src={image.src} alt={image.alt} className="size-full object-cover transition-transform duration-500 group-hover:scale-105" style={{objectPosition:image.position}}/><span className="absolute inset-0 grid place-items-center bg-background/60 text-xs font-bold tracking-[.2em] opacity-0 transition-opacity group-hover:opacity-100">VIEW</span></button>)}</div>{active!==null&&<div className="fixed inset-0 z-[80] grid place-items-center bg-background/95 p-4" role="dialog" aria-modal="true" aria-label="Gallery image viewer"><img src={galleryImages[active].src} alt={galleryImages[active].alt} className="max-h-[82vh] max-w-[92vw] object-contain"/><button className="absolute right-5 top-5 grid size-12 place-items-center border border-border" onClick={()=>setActive(null)} aria-label="Close gallery"><X/></button><button className="absolute left-3 top-1/2 grid size-12 place-items-center bg-surface md:left-8" onClick={()=>setActive((active-1+galleryImages.length)%galleryImages.length)} aria-label="Previous image"><ChevronLeft/></button><button className="absolute right-3 top-1/2 grid size-12 place-items-center bg-surface md:right-8" onClick={()=>setActive((active+1)%galleryImages.length)} aria-label="Next image"><ChevronRight/></button></div>}</>;
}
